as_strong_train_classes = ['Accelerating, revving, vroom',
                           'Air brake',
                           'Air conditioning',
                           'Air horn, truck horn',
                           'Aircraft',
                           'Aircraft engine',
                           'Alarm',
                           'Alarm clock',
                           'Alert',
                           'Ambulance (siren)',
                           'Animal',
                           'Applause',
                           'Arrow',
                           'Artillery fire',
                           'Audio logo',
                           'Babbling',
                           'Baby cry, infant cry',
                           'Baby laughter',
                           'Background noise',
                           'Bang',
                           'Bark',
                           'Basketball bounce',
                           'Bathroom sounds',
                           'Bathtub (filling or washing)',
                           'Battle cry',
                           'Bee, wasp, etc.',
                           'Beep, bleep',
                           'Bell',
                           'Bellow',
                           'Belly laugh',
                           'Bicycle bell',
                           'Bicycle, tricycle',
                           'Bird',
                           'Bird flight, flapping wings',
                           'Bird vocalization, bird call, bird song',
                           'Biting',
                           'Bleat',
                           'Blender, food processor',
                           'Boat, Water vehicle',
                           'Boiling',
                           'Boing',
                           'Booing',
                           'Boom',
                           'Bouncing',
                           'Bow-wow',
                           'Breaking',
                           'Breathing',
                           'Brief tone',
                           'Burping, eructation',
                           'Burst, pop',
                           'Bus',
                           'Busy signal',
                           'Buzz',
                           'Buzzer',
                           'Cacophony',
                           'Camera',
                           'Canidae, wild dogs, wolves',
                           'Cap gun',
                           'Car',
                           'Car alarm',
                           'Car passing by',
                           'Carbon monoxide detector, CO detector',
                           'Cart',
                           'Cash register',
                           'Cat',
                           'Caterwaul',
                           'Cattle, bovinae',
                           'Caw',
                           'Cellphone buzz, vibrating alert',
                           'Chain',
                           'Chainsaw',
                           'Change ringing (campanology)',
                           'Channel, environment and background',
                           'Chant',
                           'Cheering',
                           'Chewing, mastication',
                           'Chicken, rooster',
                           'Child singing',
                           'Child speech, kid speaking',
                           'Children playing',
                           'Children shouting',
                           'Chime',
                           'Chipmunk',
                           'Chirp tone',
                           'Chirp, tweet',
                           'Choir',
                           'Chop',
                           'Chopping (food)',
                           'Chorus effect',
                           'Chuckle, chortle',
                           'Church bell',
                           'Civil defense siren',
                           'Clang',
                           'Clapping',
                           'Clatter',
                           'Clickety-clack',
                           'Clicking',
                           'Clip-clop',
                           'Clock',
                           'Cluck',
                           'Clunk',
                           'Coin (dropping)',
                           'Computer keyboard',
                           'Conversation',
                           'Coo',
                           'Cough',
                           'Cowbell',
                           'Crack',
                           'Crackle',
                           'Creak',
                           'Cricket',
                           'Croak',
                           'Crockery breaking and smashing',
                           'Crow',
                           'Crowd',
                           'Crowing, cock-a-doodle-doo',
                           'Crumpling, crinkling',
                           'Crunch',
                           'Crushing',
                           'Crying, sobbing',
                           'Cupboard open or close',
                           'Cutlery, silverware',
                           'Deformable shell',
                           "Dental drill, dentist's drill",
                           'Dial tone',
                           'Digestive',
                           'Ding',
                           'Ding-dong',
                           'Dishes, pots, and pans',
                           'Distortion',
                           'Dog',
                           'Domestic animals, pets',
                           'Dong, bong',
                           'Donkey, ass',
                           'Door',
                           'Doorbell',
                           'Drawer open or close',
                           'Drill',
                           'Drip',
                           'Duck call (hunting tool)',
                           'Ducks, geese, waterfowl',
                           'Echo',
                           'Effects unit',
                           'Electric rotor drone, quadcopter',
                           'Electric shaver, electric razor',
                           'Electric toothbrush',
                           'Electronic tuner',
                           'Emergency vehicle',
                           'Engine',
                           'Engine knocking',
                           'Engine starting',
                           'Environmental noise',
                           'Error signal',
                           'Eruption',
                           'Explosion',
                           'Fart',
                           'Female singing',
                           'Female speech, woman speaking',
                           'Filing (rasp)',
                           'Fill (with liquid)',
                           'Finger snapping',
                           'Fire',
                           'Fire alarm',
                           'Fire engine, fire truck (siren)',
                           'Firecracker',
                           'Fireworks',
                           'Fixed-wing aircraft, airplane',
                           'Fizz',
                           'Flap',
                           'Fly, housefly',
                           'Foghorn',
                           'Fowl',
                           'Frog',
                           'Frying (food)',
                           'Fusillade',
                           'Gargling',
                           'Gasp',
                           'Gears',
                           'Generic impact sounds',
                           'Giggle',
                           'Glass',
                           'Glass chink, clink',
                           'Glass shatter',
                           'Goat',
                           'Gobble',
                           'Grind',
                           'Groan',
                           'Growling',
                           'Grunt',
                           'Gull, seagull',
                           'Gunshot, gunfire',
                           'Gurgling, bubbling',
                           'Gush',
                           'Hair dryer',
                           'Hammer',
                           'Hands',
                           'Heart sounds, heartbeat',
                           'Heavy engine (low frequency)',
                           'Helicopter',
                           'Hiccup',
                           'Hiss',
                           'Honk',
                           'Hoot',
                           'Horse',
                           'Howl',
                           'Howl (wind)',
                           'Hubbub, speech noise, speech babble',
                           'Hum',
                           'Human group actions',
                           'Human locomotion',
                           'Human sounds',
                           'Human voice',
                           'Humming',
                           'Ice cream truck, ice cream van',
                           'Idling',
                           'Insect',
                           'Inside, large room or hall',
                           'Inside, public space',
                           'Inside, small room',
                           'Jackhammer',
                           'Jet engine',
                           'Jingle bell',
                           'Jingle, tinkle',
                           'Kettle whistle',
                           'Keypress tone',
                           'Keys jangling',
                           'Kitchen and dining room sounds',
                           'Knife',
                           'Knock',
                           'Laughter',
                           'Lawn mower',
                           'Light engine (high frequency)',
                           'Liquid',
                           'Livestock, farm animals, working animals',
                           'Lock',
                           'Machine gun',
                           'Mains hum',
                           'Male singing',
                           'Male speech, man speaking',
                           'Mantra',
                           'Mechanical bell',
                           'Mechanical fan',
                           'Mechanisms',
                           'Medium engine (mid frequency)',
                           'Meow',
                           'Microphone',
                           'Microwave oven',
                           'Moo',
                           'Mosquito',
                           'Motor vehicle (road)',
                           'Motorboat, speedboat',
                           'Motorcycle',
                           'Mouse',
                           'Music',
                           'Narration, monologue',
                           'Neigh, whinny',
                           'Noise',
                           'Non-motorized land vehicle',
                           'Ocean',
                           'Oink',
                           'Other sourceless',
                           'Outside, urban or manmade',
                           'Owl',
                           'Packing tape, duct tape',
                           'Pant',
                           'Pant (dog)',
                           'Paper rustling',
                           'Patter',
                           'Pig',
                           'Pigeon, dove',
                           'Ping',
                           'Plop',
                           'Police car (siren)',
                           'Pour',
                           'Power saw, circular saw, table saw',
                           'Power tool',
                           'Power windows, electric windows',
                           'Printer',
                           'Propeller, airscrew',
                           'Puff',
                           'Pulleys',
                           'Pulse',
                           'Pump (liquid)',
                           'Purr',
                           'Quack',
                           'Race car, auto racing',
                           'Radio',
                           'Rail transport',
                           'Railroad car, train wagon',
                           'Rain',
                           'Rain on surface',
                           'Raindrop',
                           'Rapping',
                           'Ratchet, pawl',
                           'Rattle',
                           'Refrigerator',
                           'Respiratory sounds',
                           'Reverberation',
                           'Reversing beeps',
                           'Ringing tone, ringback tone',
                           'Ringtone',
                           'Roar',
                           'Roaring cats (lions, tigers)',
                           'Rodents, rats, mice',
                           'Roll',
                           'Rowboat, canoe, kayak',
                           'Rub',
                           'Rumble',
                           'Run',
                           'Rustle',
                           'Sailboat, sailing ship',
                           'Sanding',
                           'Sawing',
                           'Scissors',
                           'Scrape',
                           'Scratch',
                           'Screaming',
                           'Screech',
                           'Sewing machine',
                           'Sheep',
                           'Ship',
                           'Shout',
                           'Shower',
                           'Shuffle',
                           'Shuffling cards',
                           'Sigh',
                           'Sine wave',
                           'Singing',
                           'Single-lens reflex camera',
                           'Sink (filling or washing)',
                           'Siren',
                           'Sizzle',
                           'Skateboard',
                           'Slam',
                           'Slap, smack',
                           'Sliding door',
                           'Slosh',
                           'Slurp, drinking straw',
                           'Smash, crash',
                           'Smoke detector, smoke alarm',
                           'Snake',
                           'Snap',
                           'Sneeze',
                           'Snicker',
                           'Sniff',
                           'Snoring',
                           'Snort',
                           'Snort (horse)',
                           'Sonar',
                           'Sonic boom',
                           'Sound effect',
                           'Sound equipment',
                           'Sound reproduction',
                           'Speech',
                           'Speech synthesizer',
                           'Splash, splatter',
                           'Splinter',
                           'Spray',
                           'Squawk',
                           'Squeak',
                           'Squeal',
                           'Squish',
                           'Stairs',
                           'Static',
                           'Steam',
                           'Steam whistle',
                           'Stir',
                           'Stomach rumble',
                           'Stomp, stamp',
                           'Stream, river',
                           'Subway, metro, underground',
                           'Surface contact',
                           'Sweeping',
                           'Synthetic singing',
                           'Tap',
                           'Tap dance',
                           'Tape hiss',
                           'Tearing',
                           'Telephone',
                           'Telephone bell ringing',
                           'Telephone dialing, DTMF',
                           'Television',
                           'Throat clearing',
                           'Thump, thud',
                           'Thunder',
                           'Thunderstorm',
                           'Thunk',
                           'Tick',
                           'Tick-tock',
                           'Tire squeal, skidding',
                           'Toilet flush',
                           'Tools',
                           'Toothbrush',
                           'Traffic noise, roadway noise',
                           'Train',
                           'Train horn',
                           'Train wheels squealing',
                           'Train whistle',
                           'Trickle, dribble',
                           'Truck',
                           'Tuning fork',
                           'Turkey',
                           'Typewriter',
                           'Typing',
                           'Unknown sound',
                           'Vacuum cleaner',
                           'Vehicle',
                           'Vehicle horn, car horn, honking, toot',
                           'Velcro, hook and loop fastener',
                           'Video game sound',
                           'Wail, moan',
                           'Walk, footsteps',
                           'Washing machine',
                           'Water',
                           'Water tap, faucet',
                           'Waterfall',
                           'Waves, surf',
                           'Whack, thwack',
                           'Whale vocalization',
                           'Wheeze',
                           'Whimper',
                           'Whimper (dog)',
                           'Whip',
                           'Whir',
                           'Whispering',
                           'Whistle',
                           'Whistling',
                           'White noise, pink noise',
                           'Whoop',
                           'Whoosh, swoosh, swish',
                           'Wild animals',
                           'Wildfire',
                           'Wind',
                           'Wind chime',
                           'Wind noise (microphone)',
                           'Windscreen wiper, windshield wiper',
                           'Wobble',
                           'Wolf-whistling',
                           'Wood',
                           'Writing',
                           'Yak',
                           'Yawn',
                           'Yell',
                           'Yip',
                           'Yodeling',
                           'Zing',
                           'Zipper (clothing)']

as_strong_eval_classes = ['Accelerating, revving, vroom',
                          'Air brake',
                          'Air conditioning',
                          'Air horn, truck horn',
                          'Aircraft',
                          'Aircraft engine',
                          'Alarm',
                          'Alarm clock',
                          'Ambulance (siren)',
                          'Animal',
                          'Applause',
                          'Arrow',
                          'Artillery fire',
                          'Audio logo',
                          'Babbling',
                          'Baby cry, infant cry',
                          'Baby laughter',
                          'Background noise',
                          'Bang',
                          'Bark',
                          'Basketball bounce',
                          'Bathtub (filling or washing)',
                          'Battle cry',
                          'Bee, wasp, etc.',
                          'Beep, bleep',
                          'Bell',
                          'Bellow',
                          'Belly laugh',
                          'Bicycle bell',
                          'Bicycle, tricycle',
                          'Bird',
                          'Bird flight, flapping wings',
                          'Bird vocalization, bird call, bird song',
                          'Biting',
                          'Bleat',
                          'Blender, food processor',
                          'Boat, Water vehicle',
                          'Boiling',
                          'Boing',
                          'Boom',
                          'Bouncing',
                          'Bow-wow',
                          'Breaking',
                          'Breathing',
                          'Brief tone',
                          'Burping, eructation',
                          'Burst, pop',
                          'Bus',
                          'Busy signal',
                          'Buzz',
                          'Buzzer',
                          'Cacophony',
                          'Camera',
                          'Canidae, wild dogs, wolves',
                          'Cap gun',
                          'Car',
                          'Car alarm',
                          'Car passing by',
                          'Cart',
                          'Cash register',
                          'Cat',
                          'Caterwaul',
                          'Cattle, bovinae',
                          'Caw',
                          'Cellphone buzz, vibrating alert',
                          'Chainsaw',
                          'Change ringing (campanology)',
                          'Chant',
                          'Cheering',
                          'Chewing, mastication',
                          'Chicken, rooster',
                          'Child singing',
                          'Child speech, kid speaking',
                          'Children playing',
                          'Children shouting',
                          'Chime',
                          'Chipmunk',
                          'Chirp tone',
                          'Chirp, tweet',
                          'Choir',
                          'Chop',
                          'Chopping (food)',
                          'Chorus effect',
                          'Chuckle, chortle',
                          'Church bell',
                          'Civil defense siren',
                          'Clang',
                          'Clapping',
                          'Clatter',
                          'Clickety-clack',
                          'Clicking',
                          'Clip-clop',
                          'Clock',
                          'Cluck',
                          'Coin (dropping)',
                          'Computer keyboard',
                          'Conversation',
                          'Coo',
                          'Cough',
                          'Cowbell',
                          'Crack',
                          'Crackle',
                          'Creak',
                          'Cricket',
                          'Croak',
                          'Crockery breaking and smashing',
                          'Crow',
                          'Crowd',
                          'Crowing, cock-a-doodle-doo',
                          'Crumpling, crinkling',
                          'Crunch',
                          'Crushing',
                          'Crying, sobbing',
                          'Cupboard open or close',
                          'Cutlery, silverware',
                          "Dental drill, dentist's drill",
                          'Dial tone',
                          'Ding',
                          'Ding-dong',
                          'Dishes, pots, and pans',
                          'Distortion',
                          'Dog',
                          'Domestic animals, pets',
                          'Door',
                          'Doorbell',
                          'Drawer open or close',
                          'Drill',
                          'Drip',
                          'Ducks, geese, waterfowl',
                          'Echo',
                          'Effects unit',
                          'Electric rotor drone, quadcopter',
                          'Electric shaver, electric razor',
                          'Electric toothbrush',
                          'Electronic tuner',
                          'Emergency vehicle',
                          'Engine',
                          'Engine knocking',
                          'Engine starting',
                          'Environmental noise',
                          'Eruption',
                          'Explosion',
                          'Fart',
                          'Female singing',
                          'Female speech, woman speaking',
                          'Filing (rasp)',
                          'Fill (with liquid)',
                          'Finger snapping',
                          'Fire',
                          'Fire alarm',
                          'Fire engine, fire truck (siren)',
                          'Firecracker',
                          'Fireworks',
                          'Fixed-wing aircraft, airplane',
                          'Flap',
                          'Fly, housefly',
                          'Foghorn',
                          'Fowl',
                          'Frog',
                          'Frying (food)',
                          'Fusillade',
                          'Gargling',
                          'Gasp',
                          'Gears',
                          'Generic impact sounds',
                          'Giggle',
                          'Glass',
                          'Glass chink, clink',
                          'Glass shatter',
                          'Goat',
                          'Gobble',
                          'Groan',
                          'Growling',
                          'Grunt',
                          'Gunshot, gunfire',
                          'Gurgling, bubbling',
                          'Gush',
                          'Hair dryer',
                          'Hammer',
                          'Hands',
                          'Heart murmur',
                          'Heart sounds, heartbeat',
                          'Heavy engine (low frequency)',
                          'Helicopter',
                          'Hiccup',
                          'Hiss',
                          'Honk',
                          'Hoot',
                          'Horse',
                          'Howl',
                          'Howl (wind)',
                          'Hubbub, speech noise, speech babble',
                          'Hum',
                          'Human sounds',
                          'Human voice',
                          'Humming',
                          'Ice cream truck, ice cream van',
                          'Idling',
                          'Insect',
                          'Inside, large room or hall',
                          'Inside, public space',
                          'Inside, small room',
                          'Jackhammer',
                          'Jet engine',
                          'Jingle bell',
                          'Jingle, tinkle',
                          'Keys jangling',
                          'Kitchen and dining room sounds',
                          'Knock',
                          'Laughter',
                          'Lawn mower',
                          'Light engine (high frequency)',
                          'Liquid',
                          'Livestock, farm animals, working animals',
                          'Machine gun',
                          'Mains hum',
                          'Male singing',
                          'Male speech, man speaking',
                          'Mantra',
                          'Mechanical fan',
                          'Mechanisms',
                          'Medium engine (mid frequency)',
                          'Meow',
                          'Microwave oven',
                          'Moo',
                          'Mosquito',
                          'Motor vehicle (road)',
                          'Motorboat, speedboat',
                          'Motorcycle',
                          'Mouse',
                          'Music',
                          'Narration, monologue',
                          'Neigh, whinny',
                          'Noise',
                          'Non-motorized land vehicle',
                          'Ocean',
                          'Oink',
                          'Outside, rural or natural',
                          'Outside, urban or manmade',
                          'Owl',
                          'Packing tape, duct tape',
                          'Pant',
                          'Pant (dog)',
                          'Paper rustling',
                          'Patter',
                          'Pig',
                          'Pigeon, dove',
                          'Ping',
                          'Plop',
                          'Police car (siren)',
                          'Pour',
                          'Power saw, circular saw, table saw',
                          'Power tool',
                          'Power windows, electric windows',
                          'Printer',
                          'Propeller, airscrew',
                          'Pulleys',
                          'Pulse',
                          'Pump (liquid)',
                          'Purr',
                          'Quack',
                          'Race car, auto racing',
                          'Radio',
                          'Rail transport',
                          'Railroad car, train wagon',
                          'Rain',
                          'Rain on surface',
                          'Raindrop',
                          'Rapping',
                          'Ratchet, pawl',
                          'Rattle',
                          'Respiratory sounds',
                          'Reverberation',
                          'Reversing beeps',
                          'Ringing tone, ringback tone',
                          'Ringtone',
                          'Roar',
                          'Roaring cats (lions, tigers)',
                          'Rodents, rats, mice',
                          'Roll',
                          'Rowboat, canoe, kayak',
                          'Rub',
                          'Rumble',
                          'Run',
                          'Rustle',
                          'Sailboat, sailing ship',
                          'Sanding',
                          'Sawing',
                          'Scissors',
                          'Scrape',
                          'Scratch',
                          'Screaming',
                          'Sewing machine',
                          'Sheep',
                          'Ship',
                          'Shout',
                          'Shower',
                          'Shuffle',
                          'Shuffling cards',
                          'Sigh',
                          'Silence',
                          'Sine wave',
                          'Singing',
                          'Single-lens reflex camera',
                          'Sink (filling or washing)',
                          'Siren',
                          'Sizzle',
                          'Skateboard',
                          'Slam',
                          'Slap, smack',
                          'Sliding door',
                          'Slosh',
                          'Smash, crash',
                          'Smoke detector, smoke alarm',
                          'Snake',
                          'Sneeze',
                          'Snicker',
                          'Sniff',
                          'Snoring',
                          'Snort',
                          'Snort (horse)',
                          'Sonar',
                          'Sound effect',
                          'Sound equipment',
                          'Source-ambiguous sounds',
                          'Specific impact sounds',
                          'Speech',
                          'Speech synthesizer',
                          'Splash, splatter',
                          'Splinter',
                          'Spray',
                          'Squawk',
                          'Squeak',
                          'Squeal',
                          'Squish',
                          'Stairs',
                          'Static',
                          'Steam',
                          'Steam whistle',
                          'Stir',
                          'Stomach rumble',
                          'Stomp, stamp',
                          'Stream, river',
                          'Studio recording',
                          'Subway, metro, underground',
                          'Surface contact',
                          'Synthetic singing',
                          'Tap',
                          'Tap dance',
                          'Tearing',
                          'Telephone',
                          'Telephone bell ringing',
                          'Telephone dialing, DTMF',
                          'Television',
                          'Throat clearing',
                          'Throbbing',
                          'Thump, thud',
                          'Thunder',
                          'Thunderstorm',
                          'Thunk',
                          'Tick',
                          'Tick-tock',
                          'Tire squeal, skidding',
                          'Toilet flush',
                          'Tools',
                          'Toothbrush',
                          'Traffic noise, roadway noise',
                          'Train',
                          'Train horn',
                          'Train wheels squealing',
                          'Train whistle',
                          'Trickle, dribble',
                          'Truck',
                          'Tuning fork',
                          'Turkey',
                          'Typewriter',
                          'Typing',
                          'Unknown sound',
                          'Unmodified field recording',
                          'Vacuum cleaner',
                          'Vehicle',
                          'Vehicle horn, car horn, honking, toot',
                          'Velcro, hook and loop fastener',
                          'Vibration',
                          'Video game sound',
                          'Wail, moan',
                          'Walk, footsteps',
                          'Washing machine',
                          'Water',
                          'Water tap, faucet',
                          'Waterfall',
                          'Waves, surf',
                          'Whack, thwack',
                          'Whale vocalization',
                          'Wheeze',
                          'Whimper',
                          'Whimper (dog)',
                          'Whip',
                          'Whir',
                          'Whispering',
                          'Whistle',
                          'Whistling',
                          'White noise, pink noise',
                          'Whoop',
                          'Whoosh, swoosh, swish',
                          'Wild animals',
                          'Wind',
                          'Wind chime',
                          'Wind noise (microphone)',
                          'Wood',
                          'Writing',
                          'Yawn',
                          'Yell',
                          'Yip',
                          'Yodeling',
                          'Zipper (clothing)']

as_weak_classes = ['A capella',
                   'Accelerating, revving, vroom',
                   'Accordion',
                   'Acoustic guitar',
                   'Afrobeat',
                   'Air brake',
                   'Air conditioning',
                   'Air horn, truck horn',
                   'Aircraft',
                   'Aircraft engine',
                   'Alarm',
                   'Alarm clock',
                   'Ambient music',
                   'Ambulance (siren)',
                   'Angry music',
                   'Animal',
                   'Applause',
                   'Arrow',
                   'Artillery fire',
                   'Babbling',
                   'Baby cry, infant cry',
                   'Baby laughter',
                   'Background music',
                   'Bagpipes',
                   'Bang',
                   'Banjo',
                   'Bark',
                   'Basketball bounce',
                   'Bass drum',
                   'Bass guitar',
                   'Bathtub (filling or washing)',
                   'Battle cry',
                   'Beatboxing',
                   'Bee, wasp, etc.',
                   'Beep, bleep',
                   'Bell',
                   'Bellow',
                   'Belly laugh',
                   'Bicycle',
                   'Bicycle bell',
                   'Bird',
                   'Bird flight, flapping wings',
                   'Bird vocalization, bird call, bird song',
                   'Biting',
                   'Bleat',
                   'Blender',
                   'Bluegrass',
                   'Blues',
                   'Boat, Water vehicle',
                   'Boiling',
                   'Boing',
                   'Boom',
                   'Bouncing',
                   'Bow-wow',
                   'Bowed string instrument',
                   'Brass instrument',
                   'Breaking',
                   'Breathing',
                   'Burping, eructation',
                   'Burst, pop',
                   'Bus',
                   'Busy signal',
                   'Buzz',
                   'Buzzer',
                   'Cacophony',
                   'Camera',
                   'Canidae, dogs, wolves',
                   'Cap gun',
                   'Car',
                   'Car alarm',
                   'Car passing by',
                   'Carnatic music',
                   'Cash register',
                   'Cat',
                   'Caterwaul',
                   'Cattle, bovinae',
                   'Caw',
                   'Cello',
                   'Chainsaw',
                   'Change ringing (campanology)',
                   'Chant',
                   'Chatter',
                   'Cheering',
                   'Chewing, mastication',
                   'Chicken, rooster',
                   'Child singing',
                   'Child speech, kid speaking',
                   'Children playing',
                   'Children shouting',
                   'Chime',
                   'Chink, clink',
                   'Chirp tone',
                   'Chirp, tweet',
                   'Choir',
                   'Chop',
                   'Chopping (food)',
                   'Chorus effect',
                   'Christian music',
                   'Christmas music',
                   'Chuckle, chortle',
                   'Church bell',
                   'Civil defense siren',
                   'Clang',
                   'Clapping',
                   'Clarinet',
                   'Classical music',
                   'Clatter',
                   'Clickety-clack',
                   'Clicking',
                   'Clip-clop',
                   'Clock',
                   'Cluck',
                   'Coin (dropping)',
                   'Computer keyboard',
                   'Conversation',
                   'Coo',
                   'Cough',
                   'Country',
                   'Cowbell',
                   'Crack',
                   'Crackle',
                   'Creak',
                   'Cricket',
                   'Croak',
                   'Crow',
                   'Crowd',
                   'Crowing, cock-a-doodle-doo',
                   'Crumpling, crinkling',
                   'Crunch',
                   'Crushing',
                   'Crying, sobbing',
                   'Cupboard open or close',
                   'Cutlery, silverware',
                   'Cymbal',
                   'Dance music',
                   "Dental drill, dentist's drill",
                   'Dial tone',
                   'Didgeridoo',
                   'Ding',
                   'Ding-dong',
                   'Disco',
                   'Dishes, pots, and pans',
                   'Distortion',
                   'Dog',
                   'Domestic animals, pets',
                   'Door',
                   'Doorbell',
                   'Double bass',
                   'Drawer open or close',
                   'Drill',
                   'Drip',
                   'Drum',
                   'Drum and bass',
                   'Drum kit',
                   'Drum machine',
                   'Drum roll',
                   'Dubstep',
                   'Duck',
                   'Echo',
                   'Effects unit',
                   'Electric guitar',
                   'Electric piano',
                   'Electric shaver, electric razor',
                   'Electric toothbrush',
                   'Electronic dance music',
                   'Electronic music',
                   'Electronic organ',
                   'Electronic tuner',
                   'Electronica',
                   'Emergency vehicle',
                   'Engine',
                   'Engine knocking',
                   'Engine starting',
                   'Environmental noise',
                   'Eruption',
                   'Exciting music',
                   'Explosion',
                   'Fart',
                   'Female singing',
                   'Female speech, woman speaking',
                   'Field recording',
                   'Filing (rasp)',
                   'Fill (with liquid)',
                   'Finger snapping',
                   'Fire',
                   'Fire alarm',
                   'Fire engine, fire truck (siren)',
                   'Firecracker',
                   'Fireworks',
                   'Fixed-wing aircraft, airplane',
                   'Flamenco',
                   'Flap',
                   'Flute',
                   'Fly, housefly',
                   'Foghorn',
                   'Folk music',
                   'Fowl',
                   'French horn',
                   'Frog',
                   'Frying (food)',
                   'Funk',
                   'Funny music',
                   'Fusillade',
                   'Gargling',
                   'Gasp',
                   'Gears',
                   'Giggle',
                   'Glass',
                   'Glockenspiel',
                   'Goat',
                   'Gobble',
                   'Gong',
                   'Goose',
                   'Gospel music',
                   'Groan',
                   'Growling',
                   'Grunge',
                   'Grunt',
                   'Guitar',
                   'Gunshot, gunfire',
                   'Gurgling',
                   'Gush',
                   'Hair dryer',
                   'Hammer',
                   'Hammond organ',
                   'Hands',
                   'Happy music',
                   'Harmonic',
                   'Harmonica',
                   'Harp',
                   'Harpsichord',
                   'Heart murmur',
                   'Heart sounds, heartbeat',
                   'Heavy engine (low frequency)',
                   'Heavy metal',
                   'Helicopter',
                   'Hi-hat',
                   'Hiccup',
                   'Hip hop music',
                   'Hiss',
                   'Honk',
                   'Hoot',
                   'Horse',
                   'House music',
                   'Howl',
                   'Hubbub, speech noise, speech babble',
                   'Hum',
                   'Humming',
                   'Ice cream truck, ice cream van',
                   'Idling',
                   'Independent music',
                   'Insect',
                   'Inside, large room or hall',
                   'Inside, public space',
                   'Inside, small room',
                   'Jackhammer',
                   'Jazz',
                   'Jet engine',
                   'Jingle (music)',
                   'Jingle bell',
                   'Jingle, tinkle',
                   'Keyboard (musical)',
                   'Keys jangling',
                   'Knock',
                   'Laughter',
                   'Lawn mower',
                   'Light engine (high frequency)',
                   'Liquid',
                   'Livestock, farm animals, working animals',
                   'Lullaby',
                   'Machine gun',
                   'Mains hum',
                   'Male singing',
                   'Male speech, man speaking',
                   'Mallet percussion',
                   'Mandolin',
                   'Mantra',
                   'Maraca',
                   'Marimba, xylophone',
                   'Mechanical fan',
                   'Mechanisms',
                   'Medium engine (mid frequency)',
                   'Meow',
                   'Microwave oven',
                   'Middle Eastern music',
                   'Moo',
                   'Mosquito',
                   'Motor vehicle (road)',
                   'Motorboat, speedboat',
                   'Motorcycle',
                   'Mouse',
                   'Music',
                   'Music for children',
                   'Music of Africa',
                   'Music of Asia',
                   'Music of Bollywood',
                   'Music of Latin America',
                   'Musical instrument',
                   'Narration, monologue',
                   'Neigh, whinny',
                   'New-age music',
                   'Noise',
                   'Ocean',
                   'Oink',
                   'Opera',
                   'Orchestra',
                   'Organ',
                   'Outside, rural or natural',
                   'Outside, urban or manmade',
                   'Owl',
                   'Pant',
                   'Patter',
                   'Percussion',
                   'Piano',
                   'Pig',
                   'Pigeon, dove',
                   'Ping',
                   'Pink noise',
                   'Pizzicato',
                   'Plop',
                   'Plucked string instrument',
                   'Police car (siren)',
                   'Pop music',
                   'Pour',
                   'Power tool',
                   'Power windows, electric windows',
                   'Printer',
                   'Progressive rock',
                   'Propeller, airscrew',
                   'Psychedelic rock',
                   'Pulleys',
                   'Pulse',
                   'Pump (liquid)',
                   'Punk rock',
                   'Purr',
                   'Quack',
                   'Race car, auto racing',
                   'Radio',
                   'Rail transport',
                   'Railroad car, train wagon',
                   'Rain',
                   'Rain on surface',
                   'Raindrop',
                   'Rapping',
                   'Ratchet, pawl',
                   'Rattle',
                   'Rattle (instrument)',
                   'Reggae',
                   'Reverberation',
                   'Reversing beeps',
                   'Rhythm and blues',
                   'Rimshot',
                   'Ringtone',
                   'Roar',
                   'Roaring cats (lions, tigers)',
                   'Rock and roll',
                   'Rock music',
                   'Rodents, rats, mice',
                   'Roll',
                   'Rowboat, canoe, kayak',
                   'Rub',
                   'Rumble',
                   'Run',
                   'Rustle',
                   'Rustling leaves',
                   'Sad music',
                   'Sailboat, sailing ship',
                   'Salsa music',
                   'Sampler',
                   'Sanding',
                   'Sawing',
                   'Saxophone',
                   'Scary music',
                   'Scissors',
                   'Scrape',
                   'Scratch',
                   'Scratching (performance technique)',
                   'Screaming',
                   'Sewing machine',
                   'Shatter',
                   'Sheep',
                   'Ship',
                   'Shofar',
                   'Shout',
                   'Shuffle',
                   'Shuffling cards',
                   'Sidetone',
                   'Sigh',
                   'Silence',
                   'Sine wave',
                   'Singing',
                   'Singing bowl',
                   'Single-lens reflex camera',
                   'Sink (filling or washing)',
                   'Siren',
                   'Sitar',
                   'Sizzle',
                   'Ska',
                   'Skateboard',
                   'Skidding',
                   'Slam',
                   'Slap, smack',
                   'Sliding door',
                   'Slosh',
                   'Smash, crash',
                   'Smoke detector, smoke alarm',
                   'Snake',
                   'Snare drum',
                   'Sneeze',
                   'Snicker',
                   'Sniff',
                   'Snoring',
                   'Snort',
                   'Sonar',
                   'Song',
                   'Soul music',
                   'Sound effect',
                   'Soundtrack music',
                   'Speech',
                   'Speech synthesizer',
                   'Splash, splatter',
                   'Splinter',
                   'Spray',
                   'Squawk',
                   'Squeak',
                   'Squeal',
                   'Squish',
                   'Static',
                   'Steam',
                   'Steam whistle',
                   'Steel guitar, slide guitar',
                   'Steelpan',
                   'Stir',
                   'Stomach rumble',
                   'Stream',
                   'String section',
                   'Strum',
                   'Subway, metro, underground',
                   'Swing music',
                   'Synthesizer',
                   'Synthetic singing',
                   'Tabla',
                   'Tambourine',
                   'Tap',
                   'Tapping (guitar technique)',
                   'Tearing',
                   'Techno',
                   'Telephone',
                   'Telephone bell ringing',
                   'Telephone dialing, DTMF',
                   'Television',
                   'Tender music',
                   'Theme music',
                   'Theremin',
                   'Throat clearing',
                   'Throbbing',
                   'Thump, thud',
                   'Thunder',
                   'Thunderstorm',
                   'Thunk',
                   'Tick',
                   'Tick-tock',
                   'Timpani',
                   'Tire squeal',
                   'Toilet flush',
                   'Tools',
                   'Toot',
                   'Toothbrush',
                   'Traditional music',
                   'Traffic noise, roadway noise',
                   'Train',
                   'Train horn',
                   'Train wheels squealing',
                   'Train whistle',
                   'Trance music',
                   'Trickle, dribble',
                   'Trombone',
                   'Truck',
                   'Trumpet',
                   'Tubular bells',
                   'Tuning fork',
                   'Turkey',
                   'Typewriter',
                   'Typing',
                   'Ukulele',
                   'Vacuum cleaner',
                   'Vehicle',
                   'Vehicle horn, car horn, honking',
                   'Vibraphone',
                   'Vibration',
                   'Video game music',
                   'Violin, fiddle',
                   'Vocal music',
                   'Wail, moan',
                   'Walk, footsteps',
                   'Water',
                   'Water tap, faucet',
                   'Waterfall',
                   'Waves, surf',
                   'Wedding music',
                   'Whack, thwack',
                   'Whale vocalization',
                   'Wheeze',
                   'Whimper',
                   'Whimper (dog)',
                   'Whip',
                   'Whir',
                   'Whispering',
                   'Whistle',
                   'Whistling',
                   'White noise',
                   'Whoop',
                   'Whoosh, swoosh, swish',
                   'Wild animals',
                   'Wind',
                   'Wind chime',
                   'Wind instrument, woodwind instrument',
                   'Wind noise (microphone)',
                   'Wood',
                   'Wood block',
                   'Writing',
                   'Yell',
                   'Yip',
                   'Yodeling',
                   'Zing',
                   'Zipper (clothing)',
                   'Zither'
                   ]
